/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DienThoaiException;
import controller.IOFile;
import controller.KhachHangDAO;
import controller.SoLuongException;
import controller.TrongException;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import model.PhieuMuon;

/**
 *
 * @author ihado
 */
public class DSKH1 extends javax.swing.JPanel {
    private JTabbedPane pr;
    public void setParent(Object tab){
        this.pr = (JTabbedPane) tab;
    }
    /**
     * Creates new form DSKH1
     */
    public DSKH1() {
        initComponents();
        setSize(900, 900);
        String[] cols = {"Ma khach hang", "Ho ten", "so dien thoai", "dia chi"};
        tm = new DefaultTableModel(cols, 0);
        jTable1.setModel(tm);
//        buttonState(true);
        them = false;
//        sua = false;
        fkhachhang = "src/controller/khachhang.txt";
        fphieumuon = "src/controller/phieumuon.txt";
        loadData();
    }
    DefaultTableModel tm;
    private boolean them, sua;
    private String fkhachhang;
    private List<KhachHang> lkhachhang;
    private String fphieumuon;
    private List<PhieuMuon> lphieumuon;

    private void loadData(){
        File f = new File(fkhachhang);
        if(f.exists()) { //ktra f ton tai chua
            //neu co
            lkhachhang = IOFile.doc(fkhachhang);
        }
        File f1 = new File(fphieumuon);
        if(f1.exists()) { //ktra f ton tai chua
            //neu co
            lphieumuon = IOFile.doc(fphieumuon);
        }
    }
    private void buttonState(boolean b){
//        btThem.setEnabled(b);
//        btCapNhat.setEnabled(!b);
//        btBoQua.setEnabled(!b);
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("Danh sách khách hàng");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm Mới");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên khách hàng");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel3.setText("Mã khách hàng");

        jTextField2.setEditable(false);

        jLabel4.setText("Tên khách hàng");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("sdt");

        jLabel6.setText("Địa chỉ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Lưu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hien thi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton4)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton1)))))
                .addGap(63, 63, 63)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        buttonState(false);
        them = true;
        if (lkhachhang!=null && lkhachhang.size()>0)
            KhachHang.setSma(lkhachhang.get(lkhachhang.size()-1).getMa()+1); //lay phan tu cuoi cung +1
        else
            lkhachhang = new ArrayList<>();
                
//neu khong co
        String tenTimKiem;
        tenTimKiem = jTextField1.getText();
        jTextField2.setText(KhachHang.getSma()+"");
        jTextField2.requestFocus();
        if(them){
            
            String hoten, dchi,sdt;
            try{
                hoten = jTextField3.getText();
                sdt = jTextField4.getText();
                dchi = jTextField5.getText();
                if(hoten.isEmpty() || dchi.isEmpty()) throw new TrongException();//ngoai le
//                dthoai = jTextField4.getText();
                if(!sdt.matches("\\d+")) throw new DienThoaiException();
                if (sdt.length() > 10 || sdt.length()<=1) throw new SoLuongException();
                int ma = Integer.parseInt(jTextField2.getText());
                KhachHang kh = new KhachHang(ma, hoten,sdt , dchi);
               
                tm.addRow(kh.toObject());
                lkhachhang.add(kh);
                buttonState(true);
                them = false;
            }catch(TrongException e){
                JOptionPane.showMessageDialog(this, "Khong de trong!!");
                jTextField2.requestFocus();
            }catch(DienThoaiException e){
                JOptionPane.showMessageDialog(this, "Dien thoai phai la so");
                jTextField4.requestFocus();
            }catch (SoLuongException e) {
                JOptionPane.showMessageDialog(this, "Dien thoai phai it hon 10 so và nhieu hon 1 so");
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        
        
                pr.setSelectedIndex(3);
                DSTruyen1 dsTruyen = (DSTruyen1) pr.getSelectedComponent();
                
                
        if(row>=0 || row<jTable1.getRowCount()){
            jTextField2.setText(tm.getValueAt(row, 0).toString());
            jTextField3.setText(tm.getValueAt(row, 1).toString());
            jTextField4.setText(tm.getValueAt(row, 2).toString());
            jTextField5.setText(tm.getValueAt(row, 3).toString());
        }
        String hoten, dchi,sdt;
//            try{
                hoten = jTextField3.getText();
                dsTruyen.setTenKH(hoten);
                KhachHang kh = KhachHangDAO.findById(Integer.parseInt(jTextField2.getText()));
                dsTruyen.setKhachHang(kh);
                
                sdt = jTextField4.getText();
                dchi = jTextField5.getText();
//                if(hoten.isEmpty() || dchi.isEmpty()) throw new TrongException();//ngoai le
////                dthoai = jTextField4.getText();
//                if(!tuoi.matches("\\d+")) throw new DienThoaiException();
//                int ma = Integer.parseInt(jTextField2.getText());
                PhieuMuon pm = new PhieuMuon(hoten, sdt);
//                KhachHang kh = new KhachHang(ma, hoten,tuoi , dchi);
                tm.setRowCount(0); // xoa het bang
                tm.addRow(pm.toObject());
                lphieumuon.add(pm);
                IOFile.viet(fphieumuon, lphieumuon);
                buttonState(true);
                them = false;
//            }catch(TrongException e){
//                JOptionPane.showMessageDialog(this, "Khong de trong!!");
//                jTextField2.requestFocus();
//            }catch(DienThoaiException e){
//                JOptionPane.showMessageDialog(this, "Dien thoai phai la so");
//                jTextField4.requestFocus();
//            }

    }//GEN-LAST:event_jTable1MouseClicked
    private void show(List<KhachHang> list){
        tm.setRowCount(0);
        for(KhachHang i:list)
            tm.addRow(i.toObject());
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        loadData();
//        tm.setRowCount(0); //xoa sach bang
//        for(KhachHang i:lkhachhang)
//            tm.addRow(i.toObject());
        List<KhachHang> lsearch = new ArrayList<>();
        String key = jTextField1.getText().trim().toLowerCase();
        try {
            if (key.length()<=0) throw new TrongException();
            if (!key.matches("\\D+")) throw new SoLuongException();
        } catch (TrongException e) {
            JOptionPane.showMessageDialog(this, "khong de trong!!");
        }catch (SoLuongException e) {
            JOptionPane.showMessageDialog(this, "khong viet so!!");
        }
        for(KhachHang i:lkhachhang)
            if(i.getTen().toLowerCase().contains(key) )
                lsearch.add(i);
        show(lsearch);
//        List<QLMS> lsearch = new ArrayList<>();
//        String key = jTextField1.getText().trim().toLowerCase();
//        for(QLMS i:lqlms)
//            if(i.getBandoc().getHoten().toLowerCase().contains(key) 
//                    || i.getSach().getTen().toLowerCase().contains(key))
//                lsearch.add(i);
//        show(lsearch);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fkhachhang, lkhachhang);
        IOFile.viet(fphieumuon, lphieumuon);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        loadData();
        tm.setRowCount(0); //xoa sach bang
        for(KhachHang i:lkhachhang)
            tm.addRow(i.toObject());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private Exception TrongException() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

//    void setParent(Class<? extends MainCNPM> aClass) {
//        throw new UnsupportedOperationException("Not supported yet.");
//        this.pr = 
//    }
}
